// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUJcFjZMNfGyCbvXqMh0PvLhKYhWiyd34',
    appId: '1:364611238805:web:4a2b6fc7dcd643e1ef149c',
    messagingSenderId: '364611238805',
    projectId: 'garbage-team-test',
    authDomain: 'garbage-team-test.firebaseapp.com',
    storageBucket: 'garbage-team-test.appspot.com',
    measurementId: 'G-XKVED2YHD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChB_DTGNs-ghOFpMx-9IvRvHnhvCG50dg',
    appId: '1:364611238805:android:2bf5368153bd6212ef149c',
    messagingSenderId: '364611238805',
    projectId: 'garbage-team-test',
    storageBucket: 'garbage-team-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlyfdNikZh8t8XRTBw2sFkapP-wrufg5U',
    appId: '1:364611238805:ios:37ddc033818857aeef149c',
    messagingSenderId: '364611238805',
    projectId: 'garbage-team-test',
    storageBucket: 'garbage-team-test.appspot.com',
    iosBundleId: 'com.example.projectoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlyfdNikZh8t8XRTBw2sFkapP-wrufg5U',
    appId: '1:364611238805:ios:9c9f29bc35194360ef149c',
    messagingSenderId: '364611238805',
    projectId: 'garbage-team-test',
    storageBucket: 'garbage-team-test.appspot.com',
    iosBundleId: 'com.example.projectoApp.RunnerTests',
  );
}
